#!/usr/bin/env bash

sudo rm -rf ./dist
gulp
node ./utils/buster.js
rsync -rv ./dist/* signafide-1:fxr/ --delete
ssh signafide-1 "sudo rm -rf /var/www/fxr/* && sudo cp -r /home/zack/fxr/* /var/www/fxr/"
